FROM python:3.11

WORKDIR /app

COPY requirements.platform.txt .

RUN pip install --no-cache-dir -r requirements.platform.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]